# Generated by Django 4.1.4 on 2022-12-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produkgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('gambar', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name': 'Produk Game',
                'verbose_name_plural': 'Produk Game',
            },
        ),
    ]
