# Generated by Django 4.1.4 on 2022-12-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nominaltopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('harga', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='img/')),
                ('produkgameid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produkgameid', to='backend.produkgame')),
            ],
            options={
                'verbose_name': 'Nominal Top Up',
                'verbose_name_plural': 'Nominal Top Up',
            },
        ),
    ]
