# Generated by Django 4.1.4 on 2022-12-30 20:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_nominaltopup'),
    ]

    operations = [
        migrations.CreateModel(
            name='statustransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Status Transaksi',
                'verbose_name_plural': 'Status Transaksi',
            },
        ),
        migrations.CreateModel(
            name='transaksitopup',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('harga', models.IntegerField()),
                ('datatransaksi', models.JSONField()),
                ('nominaltopupid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominaltopupid', to='backend.nominaltopup')),
                ('statustransaksiid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statustransaksiid', to='backend.statustransaksi')),
            ],
            options={
                'verbose_name': 'Transaksi Top Up',
                'verbose_name_plural': 'Transaksi Top Up',
            },
        ),
    ]
