# Generated by Django 4.1.4 on 2022-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_statustransaksi_transaksitopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksitopup',
            name='invoice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaksitopup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
